serviceMonitors:
  - name: backend-metrics
    selector:
      matchLabels:
        app: backend
    namespaceSelector:
      matchNames:
        - production
        - staging
    endpoints:
      - port: metrics
        interval: 15s
  - name: frontend-metrics
    selector:
      matchLabels:
        app: frontend
    namespaceSelector:
      matchNames:
        - production
        - staging
    endpoints:
      - port: metrics
        interval: 15s