apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-backend
  namespace: argocd
spec:
  project: staging
  source:
    repoURL: https://github.com/yourusername/k8s-gitops.git
    path: charts/backend
    targetRevision: HEAD
    helm:
      values: |
        replicaCount: 1
        image:
          repository: yourregistry/backend
          tag: latest
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true